### ISSUE TITLE
crash when using -Os flag at link step

### ISSUE THREAD

**Issue by parisseb** [jacobly0/llvm-project#33] opened 2023-03-12 17:20 UTC
While trying to port a light version of KhiCAS to the ti83/84, I get a 3M binary, and that's too large to load on the calc/emulator. This is much larger than what I get on monochrom Casio with the same code (2M on the Casio). The reason is that the ez80 version is compiled with -Oz, while the Casio version is compiled with -Os. But trying to compile with -Os fails at link step, with the following error:
`fatal error: error in backend: unable to legalize instruction: %83:_(s48) = G_LSHR %81:_, %84:_(s8) (in function: sdk_init)
`
The source code is available here (but I believe it it reproducible with a much smaller source)
[https://www-fourier.univ-grenoble-alpes.fr/~parisse/ti/khicas.tgz](url)
Any hope to fix this? Thanks!

**Comment by mateoconlechuga** [comment] 2023-03-31 23:37
I believe this is a duplicate of #12

**Comment by jacobly0** [comment] 2023-09-04 19:55
Duplicate of #12

**Closed as not planned by jacobly0** 2023-09-04 19:55 UTC
